version: '3.9'

services:
  authorization_service:
    container_name: authorization_service
    build: ./authorization_service
    ports:
      - "8001:8000"
    volumes:
      - ./authorization_service:/code

  menu_service:
    container_name: menu_service
    build: ./menu_service
    ports:
      - "8002:8000"
    volumes:
      - ./menu_service:/code

  krakenD:
    image: devopsfaith/krakend:watch
    container_name: krakenD
    volumes:
      - ./krakenD:/etc/krakend
    ports:
      - "8080:8080"
    command: [ "run", "-d", "-c", "/etc/krakend/krakend.json" ]
    depends_on:
      - authorization_service
      - menu_service

  mongo_menu:
    container_name: mongo_menu
    image: bitnami/mongodb
    ports:
      - "27017:27017"
    volumes:
      - ~/apps/mongo:/data/db

  mongo_users:
    container_name: mongo_user
    image: bitnami/mongodb
    ports:
      - "27018:27017"
    volumes:
      - ~/apps/mongo:/data/db